title: LungFib scRNA-seq
description: Single-cell RNA sequencing analysis of innate immune cell states in lung fibrosis
theme: just-the-docs

url: https://statshaan27.github.io
baseurl: /lungfib-scrna

markdown: kramdown
kramdown:
  math_engine: katex
  syntax_highlighter: rouge

plugins:
  - jekyll-relative-links

relative_links:
  enabled: true
  collections: true
